apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-sampler-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: twitter-sampler
    spec:
      containers:
      - name: twitter-sampler
        image: christopheryang/twitter-sampler
        ports:
        - name: tomcat-port
          containerPort: 8080
        env:
        # consume the property-like keys in environment variables
        - name: oauth_consumerKey
          valueFrom:
            configMapKeyRef:
              name: twitter-acct-config
              key: oauth.consumerKey
        - name: oauth_consumerSecret
          valueFrom:
            configMapKeyRef:
              name: twitter-acct-config
              key: oauth.consumerSecret
