apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-wordcount-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        app: twitter-wordcount
    spec:
      containers:
      - name: twitter-sampler
        image: christopheryang/twitter-wordcount
        ports:
        - name: tomcat-port
          containerPort: 8080